todoDjango/config/urls.py
from django.contrib import admin
from django.urls import path, include

# from pybo import views  # 파이보의 views 파일 가져오기


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

todoDjango/pybo/urls.py
from django.urls import path
from . import views

# app_name은 써주는게 좋다.
app_name = 'pybo'
urlpatterns = [
    path('', views.index, name='index'),
    # html에서 {% url 'pybo:index' %} 가 name='index'로 연결, views의 index 함수로 넘어가고 rander로 해당 페이지로 이동
    path('add_todo/', views.add_todo, name='add_todo'),
    path('<int:todo_id>/edit_todo/', views.edit_todo, name='edit_todo'),
    path('save_news/', views.save_news, name='save_news'),
    path('calendar/',views.CalendarView.as_view(), name='calendar'),
    path('calendartest/',views.calendartest, name='calendartest'),
    # path(r'event/new/$', views.event, name='event_new'),
    path('event/new/', views.event, name='event_new'),
    # path(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    path('event/edit/<event_id>)/', views.event, name='event_edit'),
]

todoDjango/pybo/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Todo(models.Model) :
    importance = models.IntegerField(default= '1',     # 중요도
                                     choices=[
                                         (1,'1'),
                                         (2,'2'),
                                         (3,'3'),
                                     ])
    text = models.CharField(max_length=200)
    todo_check = models.BooleanField(default = False)
    timer = models.TimeField(null = True)
    create_date = models.DateField(auto_now_add = True) # 작성 날짜

    def __str__(self):
        return self.text

# class TodoDetail(models.Model):
#     todo = models.ForeignKey(Todo, on_delete=models.CASCADE)
#     text = models.CharField(max_length=200)
#     todo_check = models.BooleanField(default = False)
#     create_date = models.DateTimeField()  # 필요한가?

class NewsSave(models.Model) :
    news_title = models.CharField(max_length=200, null= False)
    news_content = models.CharField(max_length=300, null= False)
    news_writing = models.CharField(max_length=20,null= True)
    news_image = models.URLField(max_length=200, null= True)
    news_link = models.URLField(max_length=200, null= False)

    def __str__(self):
        return self.news_title

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    @property
    def get_html_url(self):     # html에 일정의 title을 가져와서 적용
        url = reverse('pybo:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'
    
# class weatherDB(models.Model):    # api에서 그냥 가져와서 필요 x
#     timestamp = models.DateTimeField(auto_now=True, null=True, blank=True)
#     temp = models.IntegerField(blank=True, null=True)   # 온도
#     humidity = models.IntegerField(blank=True, null=True)   #습도
#     rainType = models.CharField(max_length=20, blank=True, null=True)   #한시간 동안 강수량
#     sky = models.IntegerField(blank=True, null=True)    # 하늘 상태
#     sky2 = models.IntegerField(blank=True, null=True)    # 하늘 상태

#     def __str__(self):
#         return str(self.timestamp)

todoDjango/pybo/forms.py
from django import forms
from pybo.models import *
from django.forms import ModelForm, DateInput

class TodoForm(forms.ModelForm):
    class Meta :
        model = Todo
        fields = ['importance', 'text']
        # fields = ['importance', 'text', 'timer']
        # # 연동된 html에서 값을 입력받을 때
        # 모델의 필드 중 null=False 또는 blank=False로 설정된 필드가 폼에 포함되어 있어야 db에 저장 가능.
        # 폼에서 모든 '필수' 필드에 값을 입력해야 함. 

class NewsForm(forms.ModelForm):
    class Meta :
        model = NewsSave
        fields = ['news_title','news_content','news_writing','news_image','news_link']


class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)






    
#  importance = models.IntegerField(default= '1',     # 중요도
#                                      choices=[
#                                          (1,'1'),
#                                          (2,'2'),
#                                          (3,'3'),
#                                      ])
#     timer = models.TimeField(null = True)

todoDjango/pybo/views.py
from django.shortcuts import render ,get_object_or_404, redirect
from django.utils import timezone

from datetime import datetime, timedelta
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
from django.urls import reverse

from .models import *
from .forms import  *
from .weather import proc_weather
from .crawling import newslist
from .calender import Calendar

import json
import calendar

def index(request):
    todo_list = Todo.objects.all()
    weather = proc_weather()
    newsList = newslist()
    context = {'todo_list': todo_list,
               'weather' : weather,
               'newsList': newsList}

    return render(request, 'pybo/todo_list.html', context)

def calendartest(request):
    return render(request, 'pybo/calendertest.html')


# def add_todo(request):
#     form = TodoForm()
#     return render(request, 'pybo/todo_form.html', {'form':form})


def add_todo(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid(): #유효성 검사
            todo = form.save(commit= False)
            todo.create_date = timezone.now()
            todo.save()
            return redirect('pybo:index')
    else:
        form = TodoForm()
    return render(request, 'pybo/todo_form.html', {'form': form})

def edit_todo(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.save()
            return redirect('pybo:index')
    else:
        form = TodoForm(instance=todo)
    context= {'form':form}
    return render(request, 'pybo/todo_form.html', context)

def save_news(request):
    if request.method == 'POST' :
        form = NewsSave(request.POST)
        if form.is_valid():
            news = form.save(commit=False)
            news.save()
            return redirect('pybo:index')
    else:
        form = NewsSave()
    return render(request, 'pybo/todo_list.html', {'form': form})





class CalendarView(generic.ListView):
    model = Event
    template_name = 'pybo/calender.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('day', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        
        # d = get_date(self.request.GET.get('month', None)) #적용 안됨
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

# def get_date(req_day):
#     if req_day:
#         year, month = (int(x) for x in req_day.split('-'))
#         return datetime(year, month, day=1)
#     return datetime.today()

# def prev_month(d):
#     first = d.replace(day=1)
#     prev_month = first - timedelta(days=1)
#     month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
#     return month

# def next_month(d):
#     days_in_month = calendar.monthrange(d.year, d.month)[1]
#     last = d.replace(day=days_in_month)
#     next_month = last + timedelta(days=1)
#     month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
#     return month

# ----- 날짜 변경 -----
def get_date(req_day):
    try:
        if req_day: 
            year, month, day = (int(x) for x in req_day.split('-'))
            return datetime(year, month, day=1)
    except (ValueError, TypeError):
        pass
    return datetime.today().date()
def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    a = 'day=' + str(prev_month.year) + '-' + str(prev_month.month) + '-' + str(prev_month.day)
    return a
def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    a = 'day=' + str(next_month.year) + '-' + str(next_month.month) + '-' + str(next_month.day)
    return a
# ----- 날짜 변경 -----

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
    
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('pybo:calendar'))
    return render(request, 'pybo/event.html', {'form': form})

def eventDelete(request,event_id):
    event = get_object_or_404(Event, event_id)
    event.delete()
    return redirect('pybo:calendar')

todoDjango/templates/pybo/calender.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'pybo:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'pybo:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'pybo:event_new' %}"> New Event </a>

</div>
{{ calendar }}
{% endblock %}

todoDjango/templates/pybo/calendertest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css" type="text/css">
    <title>Document</title>
    
    <script>
        $(document).ready(function() {
            calendarInit();
        });
        /*
            달력 렌더링 할 때 필요한 정보 목록 
    
            현재 월(초기값 : 현재 시간)
            금월 마지막일 날짜와 요일
            전월 마지막일 날짜와 요일
        */
    
        function calendarInit() {
    
            // 날짜 정보 가져오기
            var date = new Date(); // 현재 날짜(로컬 기준) 가져오기
            var utc = date.getTime() + (date.getTimezoneOffset() * 60 * 1000); // uct 표준시 도출
            var kstGap = 9 * 60 * 60 * 1000; // 한국 kst 기준시간 더하기
            var today = new Date(utc + kstGap); // 한국 시간으로 date 객체 만들기(오늘)
        
            var thisMonth = new Date(today.getFullYear(), today.getMonth(), today.getDate());
            // 달력에서 표기하는 날짜 객체
        
            
            var currentYear = thisMonth.getFullYear(); // 달력에서 표기하는 연
            var currentMonth = thisMonth.getMonth(); // 달력에서 표기하는 월
            var currentDate = thisMonth.getDate(); // 달력에서 표기하는 일
    
            // kst 기준 현재시간
            // console.log(thisMonth);
    
            // 캘린더 렌더링
            renderCalender(thisMonth);
    
            function renderCalender(thisMonth) {
    
                // 렌더링을 위한 데이터 정리
                currentYear = thisMonth.getFullYear();
                currentMonth = thisMonth.getMonth();
                currentDate = thisMonth.getDate();
    
                // 이전 달의 마지막 날 날짜와 요일 구하기
                var startDay = new Date(currentYear, currentMonth, 0);
                var prevDate = startDay.getDate();
                var prevDay = startDay.getDay();
    
                // 이번 달의 마지막날 날짜와 요일 구하기
                var endDay = new Date(currentYear, currentMonth + 1, 0);
                var nextDate = endDay.getDate();
                var nextDay = endDay.getDay();
    
                // console.log(prevDate, prevDay, nextDate, nextDay);
    
                // 현재 월 표기
                $('.year-month').text(currentYear + '.' + (currentMonth + 1));
    
                // 렌더링 html 요소 생성
                calendar = document.querySelector('.dates')
                calendar.innerHTML = '';
                
                // 지난달
                for (var i = prevDate - prevDay + 1; i <= prevDate; i++) {
                    calendar.innerHTML = calendar.innerHTML + '<div class="day prev disable">' + i + '</div>'
                }
                // 이번달
                for (var i = 1; i <= nextDate; i++) {
                    calendar.innerHTML = calendar.innerHTML + '<div class="day current">' + i + '</div>'
                }
                // 다음달
                for (var i = 1; i <= (7 - nextDay == 7 ? 0 : 7 - nextDay); i++) {
                    calendar.innerHTML = calendar.innerHTML + '<div class="day next disable">' + i + '</div>'
                }
    
                // 오늘 날짜 표기
                if (today.getMonth() == currentMonth) {
                    todayDate = today.getDate();
                    var currentMonthDate = document.querySelectorAll('.dates .current');
                    currentMonthDate[todayDate -1].classList.add('today');
                }
            }
    
            // 이전달로 이동
            $('.go-prev').on('click', function() {
                thisMonth = new Date(currentYear, currentMonth - 1, 1);
                renderCalender(thisMonth);
            });
    
            // 다음달로 이동
            $('.go-next').on('click', function() {
                thisMonth = new Date(currentYear, currentMonth + 1, 1);
                renderCalender(thisMonth); 
            });
        }
    </script>

    <style type="text/css">
.sec_cal {
    width: 360px;
    margin: 0 auto;
    font-family: "NotoSansR";
}

.sec_cal .cal_nav {
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: 700;
    font-size: 48px;
    line-height: 78px;
}

.sec_cal .cal_nav .year-month {
    width: 300px;
    text-align: center;
    line-height: 1;
}

.sec_cal .cal_nav .nav {
    display: flex;
    border: 1px solid #333333;
    border-radius: 5px;
}

.sec_cal .cal_nav .go-prev,
.sec_cal .cal_nav .go-next {
    display: block;
    width: 50px;
    height: 78px;
    font-size: 0;
    display: flex;
    justify-content: center;
    align-items: center;
}

.sec_cal .cal_nav .go-prev::before,
.sec_cal .cal_nav .go-next::before {
    content: "";
    display: block;
    width: 20px;
    height: 20px;
    border: 3px solid #000;
    border-width: 3px 3px 0 0;
    transition: border 0.1s;
}

.sec_cal .cal_nav .go-prev:hover::before,
.sec_cal .cal_nav .go-next:hover::before {
    border-color: #ed2a61;
}

.sec_cal .cal_nav .go-prev::before {
    transform: rotate(-135deg);
}

.sec_cal .cal_nav .go-next::before {
    transform: rotate(45deg);
}

.sec_cal .cal_wrap {
    padding-top: 40px;
    position: relative;
    margin: 0 auto;
}

.sec_cal .cal_wrap .days {
    display: flex;
    margin-bottom: 20px;
    padding-bottom: 20px;
    border-bottom: 1px solid #ddd;
}

.sec_cal .cal_wrap::after {
    top: 368px;
}

.sec_cal .cal_wrap .day {
    display:flex;
    align-items: center;
    justify-content: center;
    width: calc(100% / 7);
    text-align: left;
    color: #999;
    font-size: 12px;
    text-align: center;
    border-radius:5px
}

.current.today {background: rgb(242 242 242);}

.sec_cal .cal_wrap .dates {
    display: flex;
    flex-flow: wrap;
    height: 290px;
}

.sec_cal .cal_wrap .day:nth-child(7n -1) {
    color: #3c6ffa;
}

.sec_cal .cal_wrap .day:nth-child(7n) {
    color: #ed2a61;
}

.sec_cal .cal_wrap .day.disable {
    color: #ddd;
}

    </style>

</head>
<body>
    <div class="sec_cal">
        <div class="cal_nav">
          <a href="javascript:;" class="nav-btn go-prev">prev</a>
          <div class="year-month"></div>
          <a href="javascript:;" class="nav-btn go-next">next</a>
        </div>
        <div class="cal_wrap">
          <div class="days">
            <div class="day">MON</div>
            <div class="day">TUE</div>
            <div class="day">WED</div>
            <div class="day">THU</div>
            <div class="day">FRI</div>
            <div class="day">SAT</div>
            <div class="day">SUN</div>
          </div>
          <div class="dates"></div>
        </div>
      </div>
</body>

</html>

todoDjango/templates/pybo/event.html
<!-- cal/templates/cal/event.html -->

{'% extends 'pybo/base.html' %}

{'% block title %}
Event
{'% endblock %}

{'% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{'% url 'pybo:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{'% endblock %}

todoDjango/templates/pybo/saved_news.html
<!-- django의 HTML 코드 -->
<ul>
    <!-- edit. 리스트 두개를 한번에 받아서 출력 -->
    {%for home in data %}
    <tr>
      <td>
        <div class="row">
          <div class="col-3 p-3"><a href="{{home.link}}"><img src="{{home.image_s}}"></img></a></div>
          <div class="col-9 p-3" style="font-size:14px;">
            <div class="text-secondary" style="font-size:12px;">{{home.writing}} · 경제 메인</div>
            <a href="{{ home.link }}"><b>{{home.title}}</b></a><br>
            <div class="mt-2" style="font-size: 12px">{{home.content}}</div>
          </div>
        </div>
      </td>
    </tr>
    {%endfor%}
    <!-- -->
</ul>

todoDjango/templates/pybo/todo_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">할 일 추가</h5>
            <form action="{% url 'pybo:add_todo' %}" method="post">
                {% csrf_token %}
                <table>
                <div><select name="importance" id="importance" class="form-select form-select-sm" aria-label=".form-select-sm example"
                    value="{{ form.importance.value|default_if_none:'' }}">
                    <option selected>중요도</option>
                    <option value="1">★</option>
                    <option value="2">★★</option>
                    <option value="3">★★★</option></select>
                </div>
                <div>
                <textarea  class="form-control" name="text" id="text" aria-label="할 일"
                    value="{{ form.text.value|default_if_none:'' }}"></textarea>
                </div>
                <!-- <div > 타이머 구간 </div> -->
                <button type="submit" class="btn btn-primary">저장하기</button>
                </table>
            </form>
    </form>
</div>
{% endblock %}

todoDjango/templates/pybo/todo_list.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>투두리스트</title>
</head>


<body>
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row align-item-start">
      <div class="col">
        {% if todo_list %}
            <ul class="list-group">
            {% for todo in todo_list %}
                <li class="list-group-item">
                    <p>{% if todo.importance == true %}
                        todo.importance * '★'
                    {% endif %} {{ todo.text }}</p>
                    <div class="my-3" style="float:right">
                      <a href="{% url 'pybo:edit_todo' todo.id  %}" 
                        class="btn btn btn-outline-primary">수정</a>
                    </div>
                </li>
                
            {% endfor %}
            </ul>
        {% else %}
            <p>질문이 없습니다.</p>
        {% endif %}
        </div>
        <div class="col" style="max-width: 300px;">
        
        </div>
    </div>
    
</div>
<a href="{% url 'pybo:add_todo' %}" class="btn btn-primary">할 일 등록</a>
<div>
  <form action="{% url 'pybo:save_news' %}" method="post">
    {% csrf_token %}
  <!-- 크롤링한 뉴스.py를 db에 저장하지 않고 그대로 출력(views에만 따로 적용했음)-->
    {% for news in newsList %}  
    <div class="row">
      <div class="col-3 p-3"><a href="{{ news.link }}"><img src="{{ news.image_s }}"></img></a></div>
    <div class="col-9 p-3" style="font-size:14px;">
      <div class="text-secondary" style="font-size:12px;">{{ news.writing }}</div>
      <a href="{{ news.link }}"><b>{{ news.title }}</b></a><br>
      <div class="mt-2" style="font-size: 12px">{{ news.content }}</div>
    </div>
    <div>
      <button type="submit" class="btn btn-primary">저장하기</button>
      <!-- <a href="{% url 'pybo:save_news' %}" class="btn btn-primary">뉴스 저장</a> -->
    </div>
    {%endfor%}
  </form>
</div>

<!-- <textarea  class="form-control" name="text" id="text" aria-label="할 일"
value="{{ form.text.value|default_if_none:'' }}"></textarea> -->


{% endblock %}
<!-- <a href="{% url 'pybo:save_news' news.title news.content news.writing news.image news.link %}" class="btn btn-primary">뉴스 저장</a> -->


<!-- 
<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
-->

<!-- Vertically centered modal -->
<!-- <div class="modal-dialog modal-dialog-centered">
    ...
  </div>
</body>
</html> -->