todoDjango/config/urls.py
from django.contrib import admin
from django.urls import path, include

# from pybo import views  # 파이보의 views 파일 가져오기


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

todoDjango/pybo/urls.py
from django.urls import path
from . import views

# app_name은 써주는게 좋다.
app_name = 'pybo'
urlpatterns = [
    path('', views.index, name='index'),
    # html에서 {% url 'pybo:index' %} 가 name='index'로 연결, views의 index 함수로 넘어가고 rander로 해당 페이지로 이동
    path('add_todo/', views.add_todo, name='add_todo'),
    path('<int:todo_id>/edit_todo/', views.edit_todo, name='edit_todo'),
    path('save_news/', views.save_news, name='save_news'),
    path('calendar/',views.CalendarView.as_view(), name='calendar'),
    path('calendartest/',views.calendartest, name='calendartest'),
    # path(r'event/new/$', views.event, name='event_new'),
    path('event/new/', views.event, name='event_new'),
    # path(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    path('event/edit/<event_id>)/', views.event, name='event_edit'),
]

todoDjango/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>

<body>
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <!-- <a class="nav-link" href="#">로그인</a> -->
                </li>
                <li class="nav-item">
                    <p>{{weather}}</p>
                </li>

            </ul>
        </div>
        <div class="my-3" style="float:right">
            <a href="{% url 'pybo:calendar' %}" 
              class="btn btn btn-outline-primary">달력</a>
          </div>
    </div>

</nav>

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
 
                


{'% block script %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
crossorigin="anonymous"></script>

{'% endblock %}

</body>
</html>